In [1]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1


#  Introduction to Tensors

Notes :- torch.tensor is a multi-dimensional matrix containing element of a single data type
        torch defines 10 tensors types 

In [2]:
# scaler
scalar = torch.tensor(7)       # torch.tensor is a multi-dimensional matrix containing element of a single data type
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Random tensors 


In [16]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.6792, 0.4844, 0.6834, 0.3373],
        [0.9782, 0.3166, 0.9340, 0.9849],
        [0.4100, 0.5545, 0.6409, 0.5360]])

In [17]:
#  Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,244, 3))  # height, width, color channel (R,G,B)

random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 244, 3]), 3)

In [18]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0605, 0.8874, 0.3692, 0.2814],
        [0.7815, 0.9583, 0.9886, 0.3539],
        [0.7645, 0.4682, 0.2779, 0.0098]])

In [19]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones*random_tensor

tensor([[0.0605, 0.8874, 0.3692, 0.2814],
        [0.7815, 0.9583, 0.9886, 0.3539],
        [0.7645, 0.4682, 0.2779, 0.0098]])

# Create a range of tensors and tensors-like

In [22]:
# Use torch.range()
torch.arange(0, 1000, 77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [23]:
# creating tensor-like
one_to_zeros = torch.arange(0,10)
one_to_zeros

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
ten_zeros = torch.zeros_like(input = one_to_zeros)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatype

32-bit  torch.float32 (defult datatype in pytorch)

64-bit  torch.float64

16-bit  torch.float16

32-bit complex     torch.complex32

64 bit complex     torch.complex64

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([3, 6, 9], dtype=torch.float32,
                                          device=None,  # what device is your tansor on 
                                          requires_grad=False) # whether or not track gradients with this tensor operations
float_32_tensor , float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Manipulation Tensors (tensor operations)

Tensor operations include:
* Addition 
* subtraction
* Multiplication(element-wise
* Division 
* Matrix multipliction

In [30]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [31]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [32]:
tensor

tensor([1, 2, 3])

In [33]:
# Subtrack 10
tensor - 10

tensor([-9, -8, -7])

In [34]:
#  Try out pytorch in-built functions 
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [35]:
torch.add(tensor, 43)

tensor([44, 45, 46])

In [36]:
torch.sub(tensor, 5)

tensor([-4, -3, -2])

In [37]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication
Two types
1. Element wise multiplication
2. Matrix multiplication (dot product)

There are two main rules thet performing matrix muliplication need to satisfy:
1. The inner dimension must match
2. The resulting matrix has the shape of **outer dimensions**:

In [38]:
print(f"Equatation : {tensor * tensor}")

Equatation : tensor([1, 4, 9])


In [39]:
#Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [40]:
tensor @ tensor

tensor(14)

In [41]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 35.1 ms


# Find the min, max, mean, sum, etc (tensor aggregation)

In [42]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [43]:
# Find the min value
torch.min(x), x.min()

(tensor(0), tensor(0))

In [44]:
#Find the max value
torch.max(x), x.max()

(tensor(90), tensor(90))

In [45]:
#Find the mean 
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [46]:
#Find the mean       # the torch.main() function requries a tnesor of float32 datatype to work

torch.mean(x.type(torch.float32)) ,  x.type(torch.float32).mean()   

(tensor(45.), tensor(45.))

In [47]:
#find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the position min and max of tensors

argmin() -> return index number of minimum value

min()  -> return minimum value

In [48]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
# Find the position in tensor that has the minimum value with argmin() -> return index number 

x.argmin()        # argmin() -> return index number of minimum value
                  # min()  -> return minimum value 

tensor(0)

In [50]:
x.argmax()      # argmin() -> return index number of minimum value
                # min()  -> return minimum value 

tensor(9)

# Rshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keeps the same memory as the original tensor 
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze(બદલવું) - removes all 1 dimensons to a target tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute(અરસ પરસ બદલવું) - Return a view of the input with dimension permuted (swapped) in a certain way

In [51]:
# Let's create a tensor 
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
# Add an extra dimension
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
# Change the view
z =  x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
#Change z change x (because a view of a tensor share the same memory as the original input)

z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [55]:
# stack tensor on top of each other 
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked 

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [56]:
x_reshape

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
x_reshape.shape

torch.Size([1, 9])

In [58]:
# torch.squeeze() - remove all single dimension from a target tensor
x_squeeze = x_reshape.squeeze()

In [59]:
x_squeeze.shape

torch.Size([9])

In [60]:
# torch.unsqueeze() - add a single dimension to target tensor at a specific dim(dimension) 
x_unsqueeze = x_squeeze.unsqueeze(dim=1)
x_unsqueeze.shape

torch.Size([9, 1])

In [61]:
# torch.permute(અરસ પરસ બદલવું) - permute(અરસ પરસ બદલવું) the orignaltensor to rearrange the axis(or dim) order
x_original = torch.rand(size=(224,223,3))

x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0

print("original shape ",x_original.shape)
print("permute shape", x_permuted.shape)

original shape  torch.Size([224, 223, 3])
permute shape torch.Size([3, 224, 223])


# Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with Numpy.

In [62]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [63]:
# Let's index on our new tensor 
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [64]:
x[0,0]   #x[0][0]

tensor([1, 2, 3])

In [65]:
x[0][0][1]

tensor(2)

In [67]:
# You can also use  ":" to select "all" of a target dimension 
x[:, 0]

tensor([[1, 2, 3]])

In [68]:
# Get all values of 0th and 1st dimenions but only index 1 of 2nd dimesion
x[:,:,1]

tensor([[2, 5, 8]])

In [71]:
x[:,1,1]

tensor([5])

In [72]:
x[0,0,:]

tensor([1, 2, 3])

In [75]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3,6,9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


# PyTorch tensors & NumPy 

Numpy is scienticfic python numerical computing library.

Data in numpy, want in pytorch tensor -> torch.from_numpy(ndarray)
Pytorch tensor -> Numpy -> torch.Tensor.numpy()

PyTorch defult data-type = '32'

Numpy defult data-type = '64'

In [76]:
# Numpy array to tensor 
import torch 
import numpy as np

In [82]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  #contering numpy -> pytorch reflects numpys defult of float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [85]:
# change the value of array , will thie do to 'tensor' ?
array =  array + 1
array, tensor                # tenor can't change

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [98]:
# Tensor to numpy array
tensor = torch.ones(7)         # Tensor defult data type is '32'
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [99]:
# Change the tensor, what  happens to 'Numpy' ?

tensor = tensor + 1
tensor, numpy_tensor   # numpy can't change

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducbility (trying to take random out of random)

In short how a neural network learns:

start with random numberes -> tensor operations -> update random numbers to try and make them better represntations of the data -> again -> again -> again...

Essentially what the random seed does is "flavor" the randomness.

In [100]:
import torch

In [105]:
# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tesnor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tesnor_B)
print(random_tensor_A == random_tesnor_B)

tensor([[0.1393, 0.1136, 0.6517, 0.1885],
        [0.9155, 0.6898, 0.6331, 0.7983],
        [0.9904, 0.4739, 0.5518, 0.1312]])
tensor([[0.5903, 0.1710, 0.2155, 0.6472],
        [0.9319, 0.2147, 0.6418, 0.5362],
        [0.1500, 0.8282, 0.9659, 0.4016]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [108]:
# Let's make some random but reproducible tensors

import torch

# set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tesnor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tesnor_C)
print(random_tensor_D
print(random_tesnor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensor and PyTorch bojects on GPUs (and making faster computations)

GPUs = faster compuation on number, thanks to CUDA + NVIDIA hardware + PyTorch working scense to make everythng good

In [109]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [115]:
# create a tensor( default on CPU)

tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, device)


tensor([1, 2, 3]) cpu


In [117]:
# move tensor to GPU (if availeable)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

# Moving tensor back the CPU

In [119]:
# If tesnor is on GPU can't transform it to Numpy
tensor_on_gpu.numpy()

array([1, 2, 3], dtype=int64)